name: publish
on: [workflow_dispatch]

permissions:
    id-token: write
    attestations: write
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: JDK Setup
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: "temurin"

            - name: Gradle Setup
              uses: gradle/actions/setup-gradle@v4
              with:
                  validate-wrappers: true

            - name: Enable gradlew execution
              run: chmod +x ./gradlew

            - name: Gradle Build
              run: ./gradlew build

            - name: Attest Build Provenance
              uses: actions/attest-build-provenance@v2
              with:
                  subject-path: "build/libs/*.jar, !build/libs/*-sources.jar"

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Artifacts
                  path: |
                      build/libs/*.jar
                      !build/libs/*-sources.jar

            - name: Publish
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: Bezt1FXL
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
